development:
  adapter: postgresql
  encoding: utf8
  database: todolist_dev
  username: postgres
  password: bu
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: todolist_test
  username: postgres
  password: bu
  host: localhost